### ISSUE TITLE
a zeromemory issue

### ISSUE THREAD

**Issue by T2SU** [libft/memory#1]
https://github.com/libft/memory/blob/b592dab9d3eeac2ae2a622aac1fba7d67576ec7d/src/copy/zeromemory.c#L22

같은 포인터를 참조하기 때문에, 맨 앞 포인터만 0으로 대입되는 것 같읍니다.

**Comment by mjy9088** [comment]
5a51cc5123781e5b0eec2634c715e6e07667256f 수정했습니다
